import { createVuetify, type ThemeDefinition } from 'vuetify'
import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'

const lightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    'primary': '#5200FF',
    'secondary': '#BD00FF',
    'on-primary': '#FFFFFF',
    'on-secondary': '#FFFFFF',
    'background': '#FFFFFF',
    'surface': '#FFFFFF',
    'surface-variant': '#F8F9FA',
    'on-background': '#0D1612',
    'on-surface': '#212529',
    'on-surface-variant': '#495057',
    'grey-lighten-4': '#F8F9FA',
    'grey-lighten-3': '#E9ECEF',
    'grey-lighten-2': '#DEE2E6',
    'grey': '#ADB5BD',
    'grey-darken-2': '#495057',
    'grey-darken-4': '#212529',
    'success': '#198754',
    'error': '#DC3545',
    'warning': '#FFC107',
    'info': '#0DCAF0',
    'overlay': '#4C0084',
  },
  variables: {
    'border-color': '#E9ECEF',
    'border-opacity': 1,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
  },
}

const darkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    'primary': '#7C4DFF',
    'secondary': '#CE93D8',
    'on-primary': '#FFFFFF',
    'on-secondary': '#000000',
    'background': '#0D1612',
    'surface': '#1A1F2E',
    'surface-variant': '#252B3B',
    'on-background': '#F8F9FA',
    'on-surface': '#E9ECEF',
    'on-surface-variant': '#ADB5BD',
    'grey-lighten-4': '#212529',
    'grey-lighten-3': '#343A40',
    'grey-lighten-2': '#495057',
    'grey': '#6C757D',
    'grey-darken-2': '#ADB5BD',
    'grey-darken-4': '#E9ECEF',
    'success': '#4CAF50',
    'error': '#EF5350',
    'warning': '#FFB74D',
    'info': '#29B6F6',
    'overlay': '#4C0084',
  },
  variables: {
    'border-color': '#495057',
    'border-opacity': 1,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
  },
}

export default createVuetify({
  theme: {
    defaultTheme: 'light',
    themes: { light: lightTheme, dark: darkTheme },
  },
  defaults: {
    global: { ripple: true },
    VBtn: { rounded: true, variant: 'flat', class: 'text-none' },
    VCard: { rounded: 'lg', elevation: 0 },
    VTextField: { variant: 'outlined', rounded: 'lg', density: 'comfortable', color: 'primary' },
    VTextarea: { variant: 'outlined', rounded: 'lg', density: 'comfortable', color: 'primary' },
    VSelect: { variant: 'outlined', rounded: 'lg', density: 'comfortable', color: 'primary' },
    VAutocomplete: { variant: 'outlined', rounded: 'lg', density: 'comfortable', color: 'primary' },
    VChip: { rounded: 'sm' },
    VDialog: { rounded: 'lg' },
    VSheet: { rounded: 'lg' },
    VMenu: { rounded: 'lg' },
    VNavigationDrawer: { elevation: 0 },
    VAppBar: { elevation: 0 },
    VToolbar: { elevation: 0 },
  },
})
