name: CD-Deploy-Production

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_PORT:
        required: true

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-fe:
    runs-on: self-hosted
    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: deploy/deploy.sh
