name: CI-Orchestrator

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types:
      - closed
    branches:
      - 'main'
      - 'release/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-vue:
    uses: ./.github/workflows/ci-vue.yaml

  ci-code-scan:
    uses: ./.github/workflows/ci-code-scan.yaml
    needs: ci-vue
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_SOURCES: ${{ secrets.SONAR_SOURCES }}
