name: CI-Vue-App

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '25'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: lint code
        run: npm run lint

      - name: type check
        run: npm run type-check

      - name: run unit tests
        run: npm run test:unit
